In [36]:
import os
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [37]:
df = pd.read_csv("/data/bbg/datasets/intogen/output/collaborations/20260324_BLCA_EPorta/intogen_output/highrisk_lowrisk_mibc/20260320/steps/oncodrive3d/OTHERS_WXS_BLADDER_EPORTA_HIGHRISK_NMIBC_2026.o3d_genes.tsv", sep='\t')

In [38]:
df.columns

Index(['Gene', 'Uniprot_ID', 'pval', 'qval', 'C_gene', 'C_pos', 'C_label',
       'Pos_top_vol', 'Score_obs_sim_top_vol', 'Mut_in_gene', 'Clust_mut',
       'Clust_res', 'Mut_in_top_vol', 'Mut_in_top_cl_vol', 'PAE_top_vol',
       'pLDDT_top_vol', 'pLDDT_top_cl_vol', 'Ratio_not_in_structure',
       'Ratio_WT_mismatch', 'Mut_zero_mut_prob', 'Pos_zero_mut_prob', 'Cancer',
       'Cohort', 'F', 'Transcript_ID', 'O3D_transcript_ID',
       'Transcript_status', 'Status'],
      dtype='object')

In [39]:
# translate the list of residue coordinates into a list of genomic coordinates

INTOGEN_DATASETS = '/data/bbg/datasets/intogen/output/collaborations/20260324_BLCA_EPorta/intogen_output/highrisk_lowrisk_mibc/20260320/'
sat_datasets = os.path.join(INTOGEN_DATASETS, 'steps/boostDM/saturation')
sat_datasets

COHORTS_PATH = os.path.join(INTOGEN_DATASETS, 'cohorts.tsv')

In [40]:
def load_ttypes_map(file):

    df = pd.read_csv(file, sep='\t')
    df = df[['COHORT', 'CANCER_TYPE']]
    return df.set_index('COHORT').to_dict()['CANCER_TYPE']

ttype_map = load_ttypes_map(COHORTS_PATH)

In [62]:
def residue_to_genomic(df):

    df['CANCER_TYPE'] = df['Cohort'].map(ttype_map)
    df = df[df['Transcript_status'] != 'O3D_missing']
    dh = {'HUGO Symbol': [], 'chromosome': [], 'genomic position': [], 'CANCER_TYPE': []}
    dg = df[df['C_gene'] == 1].copy()
    for gene, ttype in dg.groupby(['Gene', 'CANCER_TYPE']).size().index:
        try:
            residues = dg[(dg['Gene'] == gene) & (dg['CANCER_TYPE'] == ttype)]['C_pos'].values[0]
            residues = list(map(int, residues.strip(" []").split()))
            saturation = pd.read_csv(f"{sat_datasets}/{gene}.vep.gz", sep='\t')
            saturation = saturation[saturation['Protein_position'] != '-']
            saturation['Protein_position'] = saturation['Protein_position'].astype(int)
            genomic_coordinates = saturation[saturation['Protein_position'].isin(residues)][['Chromosome', 'Position']].drop_duplicates()
            dh['HUGO Symbol'].extend([gene])
            dh['chromosome'].extend(['chr' + str(genomic_coordinates['Chromosome'].iloc[0])])
            dh['genomic position'].extend([','.join(map(str, genomic_coordinates['Position'].values))])
            dh['CANCER_TYPE'].extend([ttype])
        except FileNotFoundError:
            print(f"Saturation file for gene {gene} not found.")
            continue
    dh = pd.DataFrame(dh)
    return dh

In [63]:
#df.head()
dh = residue_to_genomic(df)

Saturation file for gene ACTB not found.
Saturation file for gene ADCY8 not found.
Saturation file for gene ADGRV1 not found.
Saturation file for gene AHR not found.
Saturation file for gene CCDC138 not found.
Saturation file for gene CHRD not found.
Saturation file for gene CLEC4M not found.
Saturation file for gene DIAPH2 not found.
Saturation file for gene EPG5 not found.
Saturation file for gene ERICH3 not found.
Saturation file for gene ERICH6B not found.
Saturation file for gene FHL3 not found.
Saturation file for gene FOXD4L6 not found.
Saturation file for gene FRG1 not found.
Saturation file for gene H2BC12L not found.
Saturation file for gene HS6ST3 not found.
Saturation file for gene IRF5 not found.
Saturation file for gene KLF18 not found.
Saturation file for gene MADCAM1 not found.
Saturation file for gene MROH2B not found.
Saturation file for gene NANOGP8 not found.
Saturation file for gene NCAN not found.
Saturation file for gene NPEPPS not found.
Saturation file for gene NPIPB15 not found.
Saturation file for gene NRTN not found.
Saturation file for gene NUP93 not found.
Saturation file for gene PBX2 not found.
Saturation file for gene RHOB not found.
Saturation file for gene RP1L1 not found.
Saturation file for gene SELPLG not found.
Saturation file for gene SF1 not found.
Saturation file for gene SLAMF7 not found.
Saturation file for gene TFR2 not found.
Saturation file for gene TRPV1 not found.
Saturation file for gene TSPYL4 not found.
Saturation file for gene ZAN not found.
Saturation file for gene ZIC5 not found.

In [64]:
dh

,HUGO Symbol,chromosome,genomic position,CANCER_TYPE
0,AFDN,chr6,"167889230,167889231,167889232,167951903,167951...",HIGHRISK_NMIBC
1,ERBB2,chr17,"39711939,39711940,39711941,39711954,39711955,3...",HIGHRISK_NMIBC
2,ERBB3,chr12,"56085001,56085002,56085003,56085004,56085005,5...",HIGHRISK_NMIBC
3,ERCC2,chr19,"45352527,45352528,45352529,45352557,45352558,4...",HIGHRISK_NMIBC
4,FBXW7,chr4,"152324284,152324285,152324286,152326006,152326...",HIGHRISK_NMIBC
5,FGFR3,chr4,"1801837,1801838,1801839,1801840,1801841,180184...",HIGHRISK_NMIBC
6,FUT4,chr11,"94544737,94544738,94544739",HIGHRISK_NMIBC
7,GNA13,chr17,"65014791,65014792,65014793",HIGHRISK_NMIBC
8,HRAS,chr11,"533873,533874,533875,534284,534285,534286,5342...",HIGHRISK_NMIBC
9,KRAS,chr12,"25245346,25245347,25245348,25245349,25245350,2...",HIGHRISK_NMIBC
10,PIK3CA,chr3,"179218282,179218283,179218284,179218285,179218...",HIGHRISK_NMIBC
11,RXRA,chr9,"134436504,134436505,134436506,134436510,134436...",HIGHRISK_NMIBC
12,SF3B1,chr2,"197400724,197400725,197400726,197400727,197400...",HIGHRISK_NMIBC
13,TP53,chr17,"7673747,7673748,7673749,7673750,7673751,767375...",HIGHRISK_NMIBC

In [70]:
import numpy as np
import pandas as pd

def mimic_explode(s):
    """Mimics the behavior of Series.explode() for older pandas versions."""
    # Get the length of each list to know how many times to repeat the index
    # (fillna(1) ensures that rows with NaN/missing values aren't accidentally deleted)
    lens = s.str.len().fillna(1).astype(int)
    
    # Flatten the lists into a single 1D array
    # If a value isn't a list (like NaN), wrap it in a list so it flattens correctly
    flat_data = [item for sublist in s for item in (sublist if isinstance(sublist, list) else [sublist])]
    
    # Rebuild the Series with the repeated index
    return pd.Series(flat_data, index=s.index.repeat(lens))

result = (dh.set_index(['HUGO Symbol', 'CANCER_TYPE'])
            .apply(lambda x: mimic_explode(x.str.split(',')))
            .reset_index())

result

    HUGO Symbol     CANCER_TYPE chromosome genomic position
0          AFDN  HIGHRISK_NMIBC       chr6        167889230
1          AFDN  HIGHRISK_NMIBC       chr6        167889231
2          AFDN  HIGHRISK_NMIBC       chr6        167889232
3          AFDN  HIGHRISK_NMIBC       chr6        167951903
4          AFDN  HIGHRISK_NMIBC       chr6        167951904
5          AFDN  HIGHRISK_NMIBC       chr6        167951905
6         ERBB2  HIGHRISK_NMIBC      chr17         39711939
7         ERBB2  HIGHRISK_NMIBC      chr17         39711940
8         ERBB2  HIGHRISK_NMIBC      chr17         39711941
9         ERBB2  HIGHRISK_NMIBC      chr17         39711954
10        ERBB2  HIGHRISK_NMIBC      chr17         39711955
11        ERBB2  HIGHRISK_NMIBC      chr17         39711956
12        ERBB2  HIGHRISK_NMIBC      chr17         39711963
13        ERBB2  HIGHRISK_NMIBC      chr17         39711964
14        ERBB2  HIGHRISK_NMIBC      chr17         39711965
15        ERBB3  HIGHRISK_NMIBC      chr12         56085001
16        ERBB3  HIGHRISK_NMIBC      chr12         56085002
17        ERBB3  HIGHRISK_NMIBC      chr12         56085003
18        ERBB3  HIGHRISK_NMIBC      chr12         56085004
19        ERBB3  HIGHRISK_NMIBC      chr12         56085005
20        ERBB3  HIGHRISK_NMIBC      chr12         56085006
21        ERBB3  HIGHRISK_NMIBC      chr12         56085070
22        ERBB3  HIGHRISK_NMIBC      chr12         56085071
23        ERBB3  HIGHRISK_NMIBC      chr12         56085072
24        ERBB3  HIGHRISK_NMIBC      chr12         56087869
25        ERBB3  HIGHRISK_NMIBC      chr12         56087870
26        ERBB3  HIGHRISK_NMIBC      chr12         56087871
27        ERBB3  HIGHRISK_NMIBC      chr12         56087875
28        ERBB3  HIGHRISK_NMIBC      chr12         56087876
29        ERBB3  HIGHRISK_NMIBC      chr12         56087877
30        ERBB3  HIGHRISK_NMIBC      chr12         56088021
31        ERBB3  HIGHRISK_NMIBC      chr12         56088022
32        ERBB3  HIGHRISK_NMIBC      chr12         56088023
33        ERBB3  HIGHRISK_NMIBC      chr12         56088138
34        ERBB3  HIGHRISK_NMIBC      chr12         56088139
35        ERBB3  HIGHRISK_NMIBC      chr12         56088140
36        ERBB3  HIGHRISK_NMIBC      chr12         56088653
37        ERBB3  HIGHRISK_NMIBC      chr12         56088654
38        ERBB3  HIGHRISK_NMIBC      chr12         56088655
39        ERBB3  HIGHRISK_NMIBC      chr12         56088753
40        ERBB3  HIGHRISK_NMIBC      chr12         56088754
41        ERBB3  HIGHRISK_NMIBC      chr12         56088755
42        ERBB3  HIGHRISK_NMIBC      chr12         56088822
43        ERBB3  HIGHRISK_NMIBC      chr12         56088823
44        ERBB3  HIGHRISK_NMIBC      chr12         56088824
45        ERCC2  HIGHRISK_NMIBC      chr19         45352527
46        ERCC2  HIGHRISK_NMIBC      chr19         45352528
47        ERCC2  HIGHRISK_NMIBC      chr19         45352529
48        ERCC2  HIGHRISK_NMIBC      chr19         45352557
49        ERCC2  HIGHRISK_NMIBC      chr19         45352558
50        ERCC2  HIGHRISK_NMIBC      chr19         45352559
51        ERCC2  HIGHRISK_NMIBC      chr19         45352572
52        ERCC2  HIGHRISK_NMIBC      chr19         45352573
53        ERCC2  HIGHRISK_NMIBC      chr19         45352574
54        ERCC2  HIGHRISK_NMIBC      chr19         45353084
55        ERCC2  HIGHRISK_NMIBC      chr19         45353085
56        ERCC2  HIGHRISK_NMIBC      chr19         45353086
57        ERCC2  HIGHRISK_NMIBC      chr19         45353093
58        ERCC2  HIGHRISK_NMIBC      chr19         45353094
59        ERCC2  HIGHRISK_NMIBC      chr19         45353095
60        ERCC2  HIGHRISK_NMIBC      chr19         45353096
61        ERCC2  HIGHRISK_NMIBC      chr19         45353097
62        ERCC2  HIGHRISK_NMIBC      chr19         45353098
63        ERCC2  HIGHRISK_NMIBC      chr19         45357297
64        ERCC2  HIGHRISK_NMIBC      chr19         45357298
65        ERCC2  HIGHRISK_NMIBC      chr19         45357299
66        ERCC2  HIGHRISK_NMIBC      chr19         45364312
67        ERCC2  HIGHRISK_NMIBC      chr19         45364313
68        ERCC2  HIGHRISK_NMIBC      chr19         45364314
69        ERCC2  HIGHRISK_NMIBC      chr19         45364324
70        ERCC2  HIGHRISK_NMIBC      chr19         45364325
71        ERCC2  HIGHRISK_NMIBC      chr19         45364326
72        ERCC2  HIGHRISK_NMIBC      chr19         45364428
73        ERCC2  HIGHRISK_NMIBC      chr19         45364429
74        ERCC2  HIGHRISK_NMIBC      chr19         45364430
75        ERCC2  HIGHRISK_NMIBC      chr19         45364515
76        ERCC2  HIGHRISK_NMIBC      chr19         45364516
77        ERCC2  HIGHRISK_NMIBC      chr19         45364517
78        ERCC2  HIGHRISK_NMIBC      chr19         45368732
79        ERCC2  HIGHRISK_NMIBC      chr19         45368733
80        ERCC2  HIGHRISK_NMIBC      chr19         45368734
81        ERCC2  HIGHRISK_NMIBC      chr19         45368930
82        ERCC2  HIGHRISK_NMIBC      chr19         45368931
83        ERCC2  HIGHRISK_NMIBC      chr19         45368932
84        ERCC2  HIGHRISK_NMIBC      chr19         45368939
85        ERCC2  HIGHRISK_NMIBC      chr19         45368940
86        ERCC2  HIGHRISK_NMIBC      chr19         45368941
87        ERCC2  HIGHRISK_NMIBC      chr19         45368948
88        ERCC2  HIGHRISK_NMIBC      chr19         45368949
89        ERCC2  HIGHRISK_NMIBC      chr19         45368950
90        ERCC2  HIGHRISK_NMIBC      chr19         45368951
91        ERCC2  HIGHRISK_NMIBC      chr19         45368952
92        ERCC2  HIGHRISK_NMIBC      chr19         45368953
93        ERCC2  HIGHRISK_NMIBC      chr19         45368954
94        ERCC2  HIGHRISK_NMIBC      chr19         45368955
95        ERCC2  HIGHRISK_NMIBC      chr19         45368956
96        ERCC2  HIGHRISK_NMIBC      chr19         45368960
97        ERCC2  HIGHRISK_NMIBC      chr19         45368961
98        ERCC2  HIGHRISK_NMIBC      chr19         45368962
99        ERCC2  HIGHRISK_NMIBC      chr19         45369106
100       ERCC2  HIGHRISK_NMIBC      chr19         45369107
101       ERCC2  HIGHRISK_NMIBC      chr19         45369108
102       ERCC2  HIGHRISK_NMIBC      chr19         45369115
103       ERCC2  HIGHRISK_NMIBC      chr19         45369116
104       ERCC2  HIGHRISK_NMIBC      chr19         45369117
105       ERCC2  HIGHRISK_NMIBC      chr19         45369121
106       ERCC2  HIGHRISK_NMIBC      chr19         45369122
107       ERCC2  HIGHRISK_NMIBC      chr19         45369123
108       ERCC2  HIGHRISK_NMIBC      chr19         45369127
109       ERCC2  HIGHRISK_NMIBC      chr19         45369128
110       ERCC2  HIGHRISK_NMIBC      chr19         45369129
111       ERCC2  HIGHRISK_NMIBC      chr19         45370166
112       ERCC2  HIGHRISK_NMIBC      chr19         45370167
113       ERCC2  HIGHRISK_NMIBC      chr19         45370168
114       ERCC2  HIGHRISK_NMIBC      chr19         45370169
115       ERCC2  HIGHRISK_NMIBC      chr19         45370170
116       ERCC2  HIGHRISK_NMIBC      chr19         45370171
117       ERCC2  HIGHRISK_NMIBC      chr19         45370184
118       ERCC2  HIGHRISK_NMIBC      chr19         45370185
119       ERCC2  HIGHRISK_NMIBC      chr19         45370186
120       FBXW7  HIGHRISK_NMIBC       chr4        152324284
121       FBXW7  HIGHRISK_NMIBC       chr4        152324285
122       FBXW7  HIGHRISK_NMIBC       chr4        152324286
123       FBXW7  HIGHRISK_NMIBC       chr4        152326006
124       FBXW7  HIGHRISK_NMIBC       chr4        152326007
125       FBXW7  HIGHRISK_NMIBC       chr4        152326008
126       FBXW7  HIGHRISK_NMIBC       chr4        152326012
127       FBXW7  HIGHRISK_NMIBC       chr4        152326013
128       FBXW7  HIGHRISK_NMIBC       chr4        152326014
129       FBXW7  HIGHRISK_NMIBC       chr4        152326015
130       FBXW7  HIGHRISK_NMIBC       chr4        152326016
131       FBXW7  HIGHRISK_NMIBC       chr4        152326017
132       FBXW7  HIGHRISK_NMIBC       chr4        152326090
133       FBXW7  HIGHRISK_NMIBC       chr4        152326091
134       FBXW7  HIGHRISK_NMIBC       chr4        152326092
135       FBXW7  HIGHRISK_NMIBC       chr4        152326093
136       FBXW7  HIGHRISK_NMIBC       chr4        152326094
137       FBXW7  HIGHRISK_NMIBC       chr4        152326095
138       FBXW7  HIGHRISK_NMIBC       chr4        152326102
139       FBXW7  HIGHRISK_NMIBC       chr4        152326103
140       FBXW7  HIGHRISK_NMIBC       chr4        152326104
141       FBXW7  HIGHRISK_NMIBC       chr4        152326135
142       FBXW7  HIGHRISK_NMIBC       chr4        152326136
143       FBXW7  HIGHRISK_NMIBC       chr4        152326137
144       FBXW7  HIGHRISK_NMIBC       chr4        152326150
145       FBXW7  HIGHRISK_NMIBC       chr4        152326151
146       FBXW7  HIGHRISK_NMIBC       chr4        152326152
147       FBXW7  HIGHRISK_NMIBC       chr4        152326201
148       FBXW7  HIGHRISK_NMIBC       chr4        152326202
149       FBXW7  HIGHRISK_NMIBC       chr4        152326203
150       FBXW7  HIGHRISK_NMIBC       chr4        152326213
151       FBXW7  HIGHRISK_NMIBC       chr4        152326214
152       FBXW7  HIGHRISK_NMIBC       chr4        152326215
153       FBXW7  HIGHRISK_NMIBC       chr4        152328231
154       FBXW7  HIGHRISK_NMIBC       chr4        152328232
155       FBXW7  HIGHRISK_NMIBC       chr4        152328233
156       FBXW7  HIGHRISK_NMIBC       chr4        152328348
157       FBXW7  HIGHRISK_NMIBC       chr4        152328349
158       FBXW7  HIGHRISK_NMIBC       chr4        152328350
159       FGFR3  HIGHRISK_NMIBC       chr4          1801837
160       FGFR3  HIGHRISK_NMIBC       chr4          1801838
161       FGFR3  HIGHRISK_NMIBC       chr4          1801839
162       FGFR3  HIGHRISK_NMIBC       chr4          1801840
163       FGFR3  HIGHRISK_NMIBC       chr4          1801841
164       FGFR3  HIGHRISK_NMIBC       chr4          1801842
165       FGFR3  HIGHRISK_NMIBC       chr4          1804362
166       FGFR3  HIGHRISK_NMIBC       chr4          1804363
167       FGFR3  HIGHRISK_NMIBC       chr4          1804364
168       FGFR3  HIGHRISK_NMIBC       chr4          1804365
169       FGFR3  HIGHRISK_NMIBC       chr4          1804366
170       FGFR3  HIGHRISK_NMIBC       chr4          1804367
171       FGFR3  HIGHRISK_NMIBC       chr4          1804371
172       FGFR3  HIGHRISK_NMIBC       chr4          1804372
173       FGFR3  HIGHRISK_NMIBC       chr4          1804373
174        FUT4  HIGHRISK_NMIBC      chr11         94544737
175        FUT4  HIGHRISK_NMIBC      chr11         94544738
176        FUT4  HIGHRISK_NMIBC      chr11         94544739
177       GNA13  HIGHRISK_NMIBC      chr17         65014791
178       GNA13  HIGHRISK_NMIBC      chr17         65014792
179       GNA13  HIGHRISK_NMIBC      chr17         65014793
180        HRAS  HIGHRISK_NMIBC      chr11           533873
181        HRAS  HIGHRISK_NMIBC      chr11           533874
182        HRAS  HIGHRISK_NMIBC      chr11           533875
183        HRAS  HIGHRISK_NMIBC      chr11           534284
184        HRAS  HIGHRISK_NMIBC      chr11           534285
185        HRAS  HIGHRISK_NMIBC      chr11           534286
186        HRAS  HIGHRISK_NMIBC      chr11           534287
187        HRAS  HIGHRISK_NMIBC      chr11           534288
188        HRAS  HIGHRISK_NMIBC      chr11           534289
189        KRAS  HIGHRISK_NMIBC      chr12         25245346
190        KRAS  HIGHRISK_NMIBC      chr12         25245347
191        KRAS  HIGHRISK_NMIBC      chr12         25245348
192        KRAS  HIGHRISK_NMIBC      chr12         25245349
193        KRAS  HIGHRISK_NMIBC      chr12         25245350
194        KRAS  HIGHRISK_NMIBC      chr12         25245351
195      PIK3CA  HIGHRISK_NMIBC       chr3        179218282
196      PIK3CA  HIGHRISK_NMIBC       chr3        179218283
197      PIK3CA  HIGHRISK_NMIBC       chr3        179218284
198      PIK3CA  HIGHRISK_NMIBC       chr3        179218285
199      PIK3CA  HIGHRISK_NMIBC       chr3        179218286
200      PIK3CA  HIGHRISK_NMIBC       chr3        179218287
201      PIK3CA  HIGHRISK_NMIBC       chr3        179218288
202      PIK3CA  HIGHRISK_NMIBC       chr3        179218289
203      PIK3CA  HIGHRISK_NMIBC       chr3        179218290
204      PIK3CA  HIGHRISK_NMIBC       chr3        179218294
205      PIK3CA  HIGHRISK_NMIBC       chr3        179218295
206      PIK3CA  HIGHRISK_NMIBC       chr3        179218296
207      PIK3CA  HIGHRISK_NMIBC       chr3        179218303
208      PIK3CA  HIGHRISK_NMIBC       chr3        179218304
209      PIK3CA  HIGHRISK_NMIBC       chr3        179218305
210      PIK3CA  HIGHRISK_NMIBC       chr3        179218306
211      PIK3CA  HIGHRISK_NMIBC       chr3        179218307
212      PIK3CA  HIGHRISK_NMIBC       chr3        179218308
213      PIK3CA  HIGHRISK_NMIBC       chr3        179230062
214      PIK3CA  HIGHRISK_NMIBC       chr3        179230063
215      PIK3CA  HIGHRISK_NMIBC       chr3        179230064
216      PIK3CA  HIGHRISK_NMIBC       chr3        179234206
217      PIK3CA  HIGHRISK_NMIBC       chr3        179234207
218      PIK3CA  HIGHRISK_NMIBC       chr3        179234208
219      PIK3CA  HIGHRISK_NMIBC       chr3        179234284
220      PIK3CA  HIGHRISK_NMIBC       chr3        179234285
221      PIK3CA  HIGHRISK_NMIBC       chr3        179234286
222      PIK3CA  HIGHRISK_NMIBC       chr3        179234287
223      PIK3CA  HIGHRISK_NMIBC       chr3        179234288
224      PIK3CA  HIGHRISK_NMIBC       chr3        179234289
225      PIK3CA  HIGHRISK_NMIBC       chr3        179234296
226      PIK3CA  HIGHRISK_NMIBC       chr3        179234297
227      PIK3CA  HIGHRISK_NMIBC       chr3        179234298
228      PIK3CA  HIGHRISK_NMIBC       chr3        179234302
229      PIK3CA  HIGHRISK_NMIBC       chr3        179234303
230      PIK3CA  HIGHRISK_NMIBC       chr3        179234304
231        RXRA  HIGHRISK_NMIBC       chr9        134436504
232        RXRA  HIGHRISK_NMIBC       chr9        134436505
233        RXRA  HIGHRISK_NMIBC       chr9        134436506
234        RXRA  HIGHRISK_NMIBC       chr9        134436510
235        RXRA  HIGHRISK_NMIBC       chr9        134436511
236        RXRA  HIGHRISK_NMIBC       chr9        134436512
237       SF3B1  HIGHRISK_NMIBC       chr2        197400724
238       SF3B1  HIGHRISK_NMIBC       chr2        197400725
239       SF3B1  HIGHRISK_NMIBC       chr2        197400726
240       SF3B1  HIGHRISK_NMIBC       chr2        197400727
241       SF3B1  HIGHRISK_NMIBC       chr2        197400728
242       SF3B1  HIGHRISK_NMIBC       chr2        197400729
243       SF3B1  HIGHRISK_NMIBC       chr2        197400730
244       SF3B1  HIGHRISK_NMIBC       chr2        197400731
245       SF3B1  HIGHRISK_NMIBC       chr2        197400732
246       SF3B1  HIGHRISK_NMIBC       chr2        197400847
247       SF3B1  HIGHRISK_NMIBC       chr2        197400848
248       SF3B1  HIGHRISK_NMIBC       chr2        197400849
249        TP53  HIGHRISK_NMIBC      chr17          7673747
250        TP53  HIGHRISK_NMIBC      chr17          7673748
251        TP53  HIGHRISK_NMIBC      chr17          7673749
252        TP53  HIGHRISK_NMIBC      chr17          7673750
253        TP53  HIGHRISK_NMIBC      chr17          7673751
254        TP53  HIGHRISK_NMIBC      chr17          7673752
255        TP53  HIGHRISK_NMIBC      chr17          7673762
256        TP53  HIGHRISK_NMIBC      chr17          7673763
257        TP53  HIGHRISK_NMIBC      chr17          7673764
258        TP53  HIGHRISK_NMIBC      chr17          7673765
259        TP53  HIGHRISK_NMIBC      chr17          7673766
260        TP53  HIGHRISK_NMIBC      chr17          7673767
261        TP53  HIGHRISK_NMIBC      chr17          7673771
262        TP53  HIGHRISK_NMIBC      chr17          7673772
263        TP53  HIGHRISK_NMIBC      chr17          7673773
264        TP53  HIGHRISK_NMIBC      chr17          7673774
265        TP53  HIGHRISK_NMIBC      chr17          7673775
266        TP53  HIGHRISK_NMIBC      chr17          7673776
267        TP53  HIGHRISK_NMIBC      chr17          7673777
268        TP53  HIGHRISK_NMIBC      chr17          7673778
269        TP53  HIGHRISK_NMIBC      chr17          7673779
270        TP53  HIGHRISK_NMIBC      chr17          7673780
271        TP53  HIGHRISK_NMIBC      chr17          7673781
272        TP53  HIGHRISK_NMIBC      chr17          7673782
273        TP53  HIGHRISK_NMIBC      chr17          7673786
274        TP53  HIGHRISK_NMIBC      chr17          7673787
275        TP53  HIGHRISK_NMIBC      chr17          7673788
276        TP53  HIGHRISK_NMIBC      chr17          7673792
277        TP53  HIGHRISK_NMIBC      chr17          7673793
278        TP53  HIGHRISK_NMIBC      chr17          7673794
279        TP53  HIGHRISK_NMIBC      chr17          7673795
280        TP53  HIGHRISK_NMIBC      chr17          7673796
281        TP53  HIGHRISK_NMIBC      chr17          7673797
282        TP53  HIGHRISK_NMIBC      chr17          7673798
283        TP53  HIGHRISK_NMIBC      chr17          7673799
284        TP53  HIGHRISK_NMIBC      chr17          7673800
285        TP53  HIGHRISK_NMIBC      chr17          7673801
286        TP53  HIGHRISK_NMIBC      chr17          7673802
287        TP53  HIGHRISK_NMIBC      chr17          7673803
288        TP53  HIGHRISK_NMIBC      chr17          7673804
289        TP53  HIGHRISK_NMIBC      chr17          7673805
290        TP53  HIGHRISK_NMIBC      chr17          7673806
291        TP53  HIGHRISK_NMIBC      chr17          7673807
292        TP53  HIGHRISK_NMIBC      chr17          7673808
293        TP53  HIGHRISK_NMIBC      chr17          7673809
294        TP53  HIGHRISK_NMIBC      chr17          7673819
295        TP53  HIGHRISK_NMIBC      chr17          7673820
296        TP53  HIGHRISK_NMIBC      chr17          7673821
297        TP53  HIGHRISK_NMIBC      chr17          7673822
298        TP53  HIGHRISK_NMIBC      chr17          7673823
299        TP53  HIGHRISK_NMIBC      chr17          7673824
300        TP53  HIGHRISK_NMIBC      chr17          7674189
301        TP53  HIGHRISK_NMIBC      chr17          7674190
302        TP53  HIGHRISK_NMIBC      chr17          7674191
303        TP53  HIGHRISK_NMIBC      chr17          7674195
304        TP53  HIGHRISK_NMIBC      chr17          7674196
305        TP53  HIGHRISK_NMIBC      chr17          7674197
306        TP53  HIGHRISK_NMIBC      chr17          7674201
307        TP53  HIGHRISK_NMIBC      chr17          7674202
308        TP53  HIGHRISK_NMIBC      chr17          7674203
309        TP53  HIGHRISK_NMIBC      chr17          7674213
310        TP53  HIGHRISK_NMIBC      chr17          7674214
311        TP53  HIGHRISK_NMIBC      chr17          7674215
312        TP53  HIGHRISK_NMIBC      chr17          7674219
313        TP53  HIGHRISK_NMIBC      chr17          7674220
314        TP53  HIGHRISK_NMIBC      chr17          7674221
315        TP53  HIGHRISK_NMIBC      chr17          7674222
316        TP53  HIGHRISK_NMIBC      chr17          7674223
317        TP53  HIGHRISK_NMIBC      chr17          7674224
318        TP53  HIGHRISK_NMIBC      chr17          7674228
319        TP53  HIGHRISK_NMIBC      chr17          7674229
320        TP53  HIGHRISK_NMIBC      chr17          7674230
321        TP53  HIGHRISK_NMIBC      chr17          7674231
322        TP53  HIGHRISK_NMIBC      chr17          7674232
323        TP53  HIGHRISK_NMIBC      chr17          7674233
324        TP53  HIGHRISK_NMIBC      chr17          7674237
325        TP53  HIGHRISK_NMIBC      chr17          7674238
326        TP53  HIGHRISK_NMIBC      chr17          7674239
327        TP53  HIGHRISK_NMIBC      chr17          7674240
328        TP53  HIGHRISK_NMIBC      chr17          7674241
329        TP53  HIGHRISK_NMIBC      chr17          7674242
330        TP53  HIGHRISK_NMIBC      chr17          7674243
331        TP53  HIGHRISK_NMIBC      chr17          7674244

# Emulate pipeline

In [73]:
def mimic_explode(s):
    
    """Mimics the behavior of Series.explode() for older pandas versions."""
    # Get the length of each list to know how many times to repeat the index
    # (fillna(1) ensures that rows with NaN/missing values aren't accidentally deleted)
    lens = s.str.len().fillna(1).astype(int)
    
    # Flatten the lists into a single 1D array
    # If a value isn't a list (like NaN), wrap it in a list so it flattens correctly
    flat_data = [item for sublist in s for item in (sublist if isinstance(sublist, list) else [sublist])]
    
    # Rebuild the Series with the repeated index
    return pd.Series(flat_data, index=s.index.repeat(lens))


def residue_to_genomic(df):

    """
    From an input file with the significant genes and residues from oncodrive3d output of type *.o3d_genes.tsv, 
    this function generates a dataframe with the genomic coordinates of significantly 3D clustered residues.
    """

    dg = df.copy()
    
    dh = {'HUGO Symbol': [], 'chromosome': [], 'genomic position': [], 'CANCER_TYPE': []}
    
    for gene, ttype in dg.groupby(['Gene', 'CANCER_TYPE']).size().index:
        try:
            residues = dg[(dg['Gene'] == gene) & (dg['CANCER_TYPE'] == ttype)]['C_pos'].values[0]
            residues = list(map(int, residues.strip(" []").split()))
            saturation = pd.read_csv(f"{sat_datasets}/{gene}.vep.gz", sep='\t')
            saturation['Protein_position'] = saturation['Protein_position'].astype(str)
            saturation = saturation[saturation['Protein_position'] != '-']
            saturation['Protein_position'] = saturation['Protein_position'].astype(int)
            genomic_coordinates = saturation[saturation['Protein_position'].isin(residues)][['Chromosome', 'Position']].drop_duplicates()
            dh['HUGO Symbol'].extend([gene])
            dh['chromosome'].extend(['chr' + str(genomic_coordinates['Chromosome'].iloc[0])])
            dh['genomic position'].extend([','.join(map(str, genomic_coordinates['Position'].values))])
            dh['CANCER_TYPE'].extend([ttype])
        except FileNotFoundError:
            print(f"Saturation file for gene {gene} not found.")
            continue
    dh = pd.DataFrame(dh)
    return dh


def expand_genomic_coordinates(df):
    
    """
    From a dataframe with the genomic coordinates of significantly 3D clustered residues
    per gene and tumor type, as generated by the function residue_to_genomic, 
    this function generates a dataframe with one row per genomic coordinate.
    """

    dk = (df.set_index(['HUGO Symbol', 'CANCER_TYPE'])
            .apply(lambda x: mimic_explode(x.str.split(',')))
            .reset_index())
    dk.rename(columns={'genomic position': 'pos'}, inplace=True)
    dk = dk[['chromosome', 'pos', 'CANCER_TYPE']]
    return dk

In [74]:
df = pd.read_csv('/data/bbg/datasets/boostdm_runs/boostdm-pipeline-bladder-2026/work/62/ed52bc7aa3f1b5c5cc673302da0ed3/oncodrive3d_raw.tsv.gz', sep='\t')
df

,Gene,C_gene,C_pos,CANCER_TYPE
0,FGFR3,1,[248 249 371 370 369 373 368],LOWRISK_NMIBC
1,PIK3CA,1,[ 545 546 542 1047 1043 515],LOWRISK_NMIBC
2,HRAS,1,[61 12 13],LOWRISK_NMIBC
3,CCDC138,1,[473 472],LOWRISK_NMIBC
4,CELSR2,1,[16 17],LOWRISK_NMIBC
5,AKT1,1,[17],LOWRISK_NMIBC
6,CLEC4M,1,[210],LOWRISK_NMIBC
7,PTGER4,1,[385 381],LOWRISK_NMIBC
8,ERICH3,1,[1019 1022],LOWRISK_NMIBC
9,GNA13,1,[200],LOWRISK_NMIBC
10,ABCF1,1,[9],LOWRISK_NMIBC
11,SCN4A,1,[1809],LOWRISK_NMIBC
12,ADCY8,1,[254 257 252],LOWRISK_NMIBC
13,CACNA1E,1,[838 840 836],LOWRISK_NMIBC
14,AFDN,1,[1517],LOWRISK_NMIBC
15,PIK3CA,1,[ 545 542 546 549 539 1049 1047 956 1043 ...,MIBC
16,FGFR3,1,[248 249 373 370 371],MIBC
17,TP53,1,[132 248 249 275 285 280 246 283 134 245 242 2...,MIBC
18,ERBB2,1,[310 767 280 755 277 769 733],MIBC
19,KRAS,1,[13 61 59 15 12 19],MIBC
20,RXRA,1,[427],MIBC
21,HRAS,1,[12 61 13 33],MIBC
22,FBXW7,1,[479 505 477 465 481 519 517 520 546 426 483 3...,MIBC
23,AHR,1,[350 383],MIBC
24,SF3B1,1,[860 903 897 862 902 898 894 906],MIBC
25,GNA13,1,[135 58 200],MIBC
26,KRT8,1,[31],MIBC
27,RPS3A,1,[157],MIBC
28,USP7,1,[4],MIBC
29,RHPN2,1,[73],MIBC
30,C3orf70,1,[6],MIBC
31,BMP6,1,[118],MIBC
32,ERCC2,1,[458 75 242 659 665 666 238 49 44 606 74 2...,MIBC
33,SF1,1,[157 153 154 159 162 160 203 141 144 200 205 168],MIBC
34,THAP12,1,[81 78],MIBC
35,ZNF285,1,[61 60],MIBC
36,TMEM14B,1,[108],MIBC
37,UGT2B11,1,[442 447],MIBC
38,CHRD,1,[45 46],MIBC
39,APOBR,1,[361 364],MIBC
40,NACA,1,[1122],MIBC
41,ARHGAP5,1,[489],MIBC
42,ERBB4,1,[1289 707],MIBC
43,TRIM48,1,[44],MIBC
44,MB21D2,1,[311 315],MIBC
45,DEK,1,[41],MIBC
46,RARS2,1,[6],MIBC
47,DCP1B,1,[252],MIBC
48,CREBBP,1,[1436 1482 1434 1484 1435 1664 1687],MIBC
49,C12orf43,1,[25 28],MIBC
50,KRTAP4-7,1,[121 148],MIBC
51,NFE2L2,1,[82 81 34 80 29 79 31 35 24],MIBC
52,PSG3,1,[12 11],MIBC
53,MADCAM1,1,[248 246],MIBC
54,DIAPH2,1,[ 284 280 335 1059 1069 1065 1066 376],MIBC
55,ATXN1,1,[212 211 209],MIBC
56,SELPLG,1,[137 138],MIBC
57,RHOB,1,[ 47 46 172 106 75 102],MIBC
58,KLF5,1,[414 417 419 416 418 393],MIBC
59,PRB4,1,[123],MIBC
60,ERBB3,1,[104 103 245 91 332 284],MIBC
61,DLC1,1,[741],MIBC
62,ANP32E,1,[193],MIBC
63,UBXN11,1,[490 492],MIBC
64,PBX2,1,[74 70],MIBC
65,LRRCC1,1,[6],MIBC
66,CTNNB1,1,[34 37 32 33],MIBC
67,RHOA,1,[ 46 47 28 161 20 172 17 22 26 168 118 1...,MIBC
68,EP300,1,[1400 1448 1446 1445 1414 1399 1627 1470 1409 ...,MIBC
69,KRTAP5-2,1,[20],MIBC
70,MYO1E,1,[459],MIBC
71,PRDM8,1,[212],MIBC
72,BAP1,1,[ 91 184 169 168 190 182 90],MIBC
73,AK2,1,[201 199],MIBC
74,DMKN,1,[282 284 280],MIBC
75,ACSS3,1,[290 287],MIBC
76,ERICH6B,1,[138 136 139 135],MIBC
77,TMPRSS13,1,[77 78 74],MIBC
78,KCNMA1,1,[13],MIBC
79,ETV4,1,[30],MIBC
80,SLC35G5,1,[103],MIBC
81,MEGF9,1,[30],MIBC
82,CABLES1,1,[99],MIBC
83,CUL1,1,[485 483],MIBC
84,EPAS1,1,[474],MIBC
85,RPS18,1,[77],MIBC
86,FOXD4L1,1,[155],MIBC
87,FAM8A1,1,[353 355 244 346 93 94 357 350],MIBC
88,ANKHD1,1,[60],MIBC
89,TRIM13,1,[407],MIBC
90,TTLL11,1,[31 26],MIBC
91,CYP2A6,1,[ 80 368 59 64 369],MIBC
92,ASXL2,1,[334 330],MIBC
93,MROH2B,1,[1109],MIBC
94,FUT4,1,[202],MIBC
95,RTKN2,1,[327],MIBC
96,ABCD1,1,[608 606],MIBC
97,TFPI2,1,[222],MIBC
98,ARSD,1,[223 221],MIBC
99,SIMC1,1,[52 50 53],MIBC
100,UNCX,1,[136 146 133],MIBC
101,IRX5,1,[400 401 402 398],MIBC
102,BRAF,1,[594 596 470 469 581 464 485 578 600 575],MIBC
103,KMT2D,1,[5432 5454 5457 5214 5433 5462 5230 5229 5179 ...,MIBC
104,FGFR3,1,[248 249 373 371 370],HIGHRISK_NMIBC
105,PIK3CA,1,[ 545 542 546 540 539 538 1049 1043 1047 ...,HIGHRISK_NMIBC
106,TP53,1,[282 274 240 281 250 275 132 242 273 278 276 2...,HIGHRISK_NMIBC
107,ERBB2,1,[305 310 313],HIGHRISK_NMIBC
108,HRAS,1,[12 61 13],HIGHRISK_NMIBC
109,FBXW7,1,[505 516 546 519 479 545 465 483 520 500 548 5...,HIGHRISK_NMIBC
110,ERICH6B,1,[139],HIGHRISK_NMIBC
111,RXRA,1,[429 427],HIGHRISK_NMIBC
112,GNA13,1,[200],HIGHRISK_NMIBC
113,KLF18,1,[862],HIGHRISK_NMIBC
114,MROH2B,1,[1109 1112],HIGHRISK_NMIBC
115,FOXD4L6,1,[366],HIGHRISK_NMIBC
116,CCDC138,1,[473 472],HIGHRISK_NMIBC
117,FUT4,1,[202],HIGHRISK_NMIBC
118,SF3B1,1,[903 901 862 902],HIGHRISK_NMIBC
119,ERCC2,1,[ 75 238 18 242 665 44 42 76 46 209 79 4...,HIGHRISK_NMIBC
120,AHR,1,[383],HIGHRISK_NMIBC
121,MADCAM1,1,[248 246],HIGHRISK_NMIBC
122,NANOGP8,1,[16],HIGHRISK_NMIBC
123,NPIPB15,1,[44],HIGHRISK_NMIBC
124,KRAS,1,[12 13],HIGHRISK_NMIBC
125,CLEC4M,1,[210],HIGHRISK_NMIBC
126,SELPLG,1,[226],HIGHRISK_NMIBC
127,ZAN,1,[714],HIGHRISK_NMIBC
128,NUP93,1,[15 14],HIGHRISK_NMIBC
129,RHOB,1,[172 47 169],HIGHRISK_NMIBC
130,NRTN,1,[190 193 171],HIGHRISK_NMIBC
131,ERBB3,1,[245 81 82 104 332 232 329 284 355 230],HIGHRISK_NMIBC
132,H2BC12L,1,[28],HIGHRISK_NMIBC
133,FHL3,1,[133],HIGHRISK_NMIBC
134,FRG1,1,[26],HIGHRISK_NMIBC
135,TFR2,1,[387 385 365],HIGHRISK_NMIBC
136,DIAPH2,1,[1063 280 1060],HIGHRISK_NMIBC
137,ACTB,1,[ 14 158],HIGHRISK_NMIBC
138,TSPYL4,1,[110],HIGHRISK_NMIBC
139,RP1L1,1,[1866],HIGHRISK_NMIBC
140,IRF5,1,[191],HIGHRISK_NMIBC
141,ERICH3,1,[1022],HIGHRISK_NMIBC
142,PBX2,1,[70],HIGHRISK_NMIBC
143,TRPV1,1,[621],HIGHRISK_NMIBC
144,SF1,1,[154 151 150 157],HIGHRISK_NMIBC
145,HS6ST3,1,[81 82],HIGHRISK_NMIBC
146,ADCY8,1,[250 252 254 246],HIGHRISK_NMIBC
147,ZIC5,1,[438 444 458 377],HIGHRISK_NMIBC
148,AFDN,1,[ 305 1517],HIGHRISK_NMIBC
149,SLAMF7,1,[184],HIGHRISK_NMIBC
150,CHRD,1,[45 46],HIGHRISK_NMIBC
151,NCAN,1,[1288],HIGHRISK_NMIBC
152,NPEPPS,1,[322],HIGHRISK_NMIBC
153,EPG5,1,[1865 1864 1867],HIGHRISK_NMIBC
154,ADGRV1,1,[4503 4501 4500 4504],HIGHRISK_NMIBC

In [75]:
dh = residue_to_genomic(df)

Saturation file for gene ABCD1 not found.
Saturation file for gene ABCF1 not found.
Saturation file for gene ACSS3 not found.
Saturation file for gene ACTB not found.
Saturation file for gene ADCY8 not found.
Saturation file for gene ADCY8 not found.
Saturation file for gene ADGRV1 not found.
Saturation file for gene AHR not found.
Saturation file for gene AHR not found.
Saturation file for gene AK2 not found.
Saturation file for gene ANKHD1 not found.
Saturation file for gene ANP32E not found.
Saturation file for gene APOBR not found.
Saturation file for gene ARSD not found.
Saturation file for gene ATXN1 not found.
Saturation file for gene C12orf43 not found.
Saturation file for gene C3orf70 not found.
Saturation file for gene CABLES1 not found.
Saturation file for gene CACNA1E not found.
Saturation file for gene CCDC138 not found.
Saturation file for gene CCDC138 not found.
Saturation file for gene CELSR2 not found.
Saturation file for gene CHRD not found.
Saturation file for gene CHRD not found.
Saturation file for gene CLEC4M not found.
Saturation file for gene CLEC4M not found.
Saturation file for gene CTNNB1 not found.
Saturation file for gene CUL1 not found.
Saturation file for gene CYP2A6 not found.
Saturation file for gene DCP1B not found.
Saturation file for gene DIAPH2 not found.
Saturation file for gene DIAPH2 not found.
Saturation file for gene DLC1 not found.
Saturation file for gene DMKN not found.
Saturation file for gene EPAS1 not found.
Saturation file for gene EPG5 not found.
Saturation file for gene ERBB4 not found.
Saturation file for gene ERICH3 not found.
Saturation file for gene ERICH3 not found.
Saturation file for gene ERICH6B not found.
Saturation file for gene ERICH6B not found.
Saturation file for gene FAM8A1 not found.
Saturation file for gene FHL3 not found.
Saturation file for gene FOXD4L1 not found.
Saturation file for gene FOXD4L6 not found.
Saturation file for gene FRG1 not found.
Saturation file for gene H2BC12L not found.
Saturation file for gene HS6ST3 not found.
Saturation file for gene IRF5 not found.
Saturation file for gene IRX5 not found.
Saturation file for gene KCNMA1 not found.
Saturation file for gene KLF18 not found.
Saturation file for gene KLF5 not found.
Saturation file for gene KRT8 not found.
Saturation file for gene KRTAP4-7 not found.
Saturation file for gene KRTAP5-2 not found.
Saturation file for gene LRRCC1 not found.
Saturation file for gene MADCAM1 not found.
Saturation file for gene MADCAM1 not found.
Saturation file for gene MEGF9 not found.
Saturation file for gene MROH2B not found.
Saturation file for gene MROH2B not found.
Saturation file for gene MYO1E not found.
Saturation file for gene NANOGP8 not found.
Saturation file for gene NCAN not found.
Saturation file for gene NFE2L2 not found.
Saturation file for gene NPEPPS not found.
Saturation file for gene NPIPB15 not found.
Saturation file for gene NRTN not found.
Saturation file for gene NUP93 not found.
Saturation file for gene PBX2 not found.
Saturation file for gene PBX2 not found.
Saturation file for gene PRB4 not found.
Saturation file for gene PRDM8 not found.
Saturation file for gene PSG3 not found.
Saturation file for gene PTGER4 not found.
Saturation file for gene RARS2 not found.
Saturation file for gene RHOB not found.
Saturation file for gene RHOB not found.
Saturation file for gene RP1L1 not found.
Saturation file for gene RPS18 not found.
Saturation file for gene RPS3A not found.
Saturation file for gene RTKN2 not found.
Saturation file for gene SCN4A not found.
Saturation file for gene SELPLG not found.
Saturation file for gene SELPLG not found.
Saturation file for gene SF1 not found.
Saturation file for gene SF1 not found.
Saturation file for gene SIMC1 not found.
Saturation file for gene SLAMF7 not found.
Saturation file for gene SLC35G5 not found.
Saturation file for gene TFPI2 not found.
Saturation file for gene TFR2 not found.
Saturation file for gene THAP12 not found.
Saturation file for gene TMEM14B not found.
Saturation file for gene TMPRSS13 not found.
Saturation file for gene TRIM13 not found.
Saturation file for gene TRIM48 not found.
Saturation file for gene TRPV1 not found.
Saturation file for gene TSPYL4 not found.
Saturation file for gene TTLL11 not found.
Saturation file for gene UBXN11 not found.
Saturation file for gene UGT2B11 not found.
Saturation file for gene UNCX not found.
Saturation file for gene ZAN not found.
Saturation file for gene ZIC5 not found.
Saturation file for gene ZNF285 not found.

In [76]:
dh

,HUGO Symbol,chromosome,genomic position,CANCER_TYPE
0,AFDN,chr6,"167889230,167889231,167889232,167951903,167951...",HIGHRISK_NMIBC
1,AFDN,chr6,"167951903,167951904,167951905",LOWRISK_NMIBC
2,AKT1,chr14,"104780212,104780213,104780214",LOWRISK_NMIBC
3,ARHGAP5,chr14,"32092134,32092135,32092136",MIBC
4,ASXL2,chr2,"25756052,25756053,25756054,25756064,25756065,2...",MIBC
5,BAP1,chr3,"52407184,52407185,52407186,52407202,52407203,5...",MIBC
6,BMP6,chr6,"7727307,7727308,7727309",MIBC
7,BRAF,chr7,"140753335,140753336,140753337,140753347,140753...",MIBC
8,CREBBP,chr16,"3731303,3731304,3731305,3731372,3731373,373137...",MIBC
9,DEK,chr6,"18263865,18263866,18263867",MIBC
10,EP300,chr22,"41169525,41169526,41169527,41169528,41169529,4...",MIBC
11,ERBB2,chr17,"39711939,39711940,39711941,39711954,39711955,3...",HIGHRISK_NMIBC
12,ERBB2,chr17,"39710409,39710410,39710411,39710418,39710419,3...",MIBC
13,ERBB3,chr12,"56085001,56085002,56085003,56085004,56085005,5...",HIGHRISK_NMIBC
14,ERBB3,chr12,"56085031,56085032,56085033,56085067,56085068,5...",MIBC
15,ERCC2,chr19,"45352527,45352528,45352529,45352557,45352558,4...",HIGHRISK_NMIBC
16,ERCC2,chr19,"45352527,45352528,45352529,45352554,45352555,4...",MIBC
17,ETV4,chr17,"43545338,43545339,43545340",MIBC
18,FBXW7,chr4,"152324284,152324285,152324286,152326006,152326...",HIGHRISK_NMIBC
19,FBXW7,chr4,"152326012,152326013,152326014,152326030,152326...",MIBC
20,FGFR3,chr4,"1801837,1801838,1801839,1801840,1801841,180184...",HIGHRISK_NMIBC
21,FGFR3,chr4,"1801837,1801838,1801839,1801840,1801841,180184...",LOWRISK_NMIBC
22,FGFR3,chr4,"1801837,1801838,1801839,1801840,1801841,180184...",MIBC
23,FUT4,chr11,"94544737,94544738,94544739",HIGHRISK_NMIBC
24,FUT4,chr11,"94544737,94544738,94544739",MIBC
25,GNA13,chr17,"65014791,65014792,65014793",HIGHRISK_NMIBC
26,GNA13,chr17,"65014791,65014792,65014793",LOWRISK_NMIBC
27,GNA13,chr17,"65014791,65014792,65014793,65053607,65053608,6...",MIBC
28,HRAS,chr11,"533873,533874,533875,534284,534285,534286,5342...",HIGHRISK_NMIBC
29,HRAS,chr11,"533873,533874,533875,534284,534285,534286,5342...",LOWRISK_NMIBC
30,HRAS,chr11,"533873,533874,533875,534224,534225,534226,5342...",MIBC
31,KMT2D,chr12,"49022306,49022307,49022308,49022321,49022322,4...",MIBC
32,KRAS,chr12,"25245346,25245347,25245348,25245349,25245350,2...",HIGHRISK_NMIBC
33,KRAS,chr12,"25227341,25227342,25227343,25227347,25227348,2...",MIBC
34,MB21D2,chr3,"192798917,192798918,192798919,192798929,192798...",MIBC
35,NACA,chr12,"56718164,56718165,56718166",MIBC
36,PIK3CA,chr3,"179218282,179218283,179218284,179218285,179218...",HIGHRISK_NMIBC
37,PIK3CA,chr3,"179218213,179218214,179218215,179218294,179218...",LOWRISK_NMIBC
38,PIK3CA,chr3,"179210285,179210286,179210287,179210291,179210...",MIBC
39,RHOA,chr3,"49360275,49360276,49360277,49360287,49360288,4...",MIBC
40,RHPN2,chr19,"33026599,33026600,33026601",MIBC
41,RXRA,chr9,"134436504,134436505,134436506,134436510,134436...",HIGHRISK_NMIBC
42,RXRA,chr9,"134436504,134436505,134436506",MIBC
43,SF3B1,chr2,"197400724,197400725,197400726,197400727,197400...",HIGHRISK_NMIBC
44,SF3B1,chr2,"197400715,197400716,197400717,197400724,197400...",MIBC
45,TP53,chr17,"7673747,7673748,7673749,7673750,7673751,767375...",HIGHRISK_NMIBC
46,TP53,chr17,"7673759,7673760,7673761,7673762,7673763,767376...",MIBC
47,USP7,chr16,"8963274,8963275,8963276",MIBC

In [80]:
# expand genomic coordinates

# Assuming 'dh' is your dataframe and the columns you want to split are in a list
# For this example, let's pretend you are splitting a column called 'VALUES'
cols_to_split = ['genomic position'] # Update this to the actual column(s) containing the commas

# 1. Split the strings into lists for the target columns
split_series = dh[cols_to_split[0]].astype(str).str.split(',')

# 2. Figure out how many items are in each list (this is our multiplier)
lens = split_series.str.len().fillna(1).astype(int)

# 3. Repeat the ENTIRE dataframe's rows based on those lengths
result_df = dh.loc[dh.index.repeat(lens)].copy()

# 4. Flatten the lists and overwrite the columns in the repeated dataframe
for col in cols_to_split:
    # Split the column
    s = dh[col].astype(str).str.split(',')
    # Flatten it
    flat_data = [item for sublist in s for item in (sublist if isinstance(sublist, list) else [sublist])]
    # Assign it back
    result_df[col] = flat_data

result_df

   HUGO Symbol chromosome genomic position     CANCER_TYPE
0         AFDN       chr6        167889230  HIGHRISK_NMIBC
0         AFDN       chr6        167889231  HIGHRISK_NMIBC
0         AFDN       chr6        167889232  HIGHRISK_NMIBC
0         AFDN       chr6        167951903  HIGHRISK_NMIBC
0         AFDN       chr6        167951904  HIGHRISK_NMIBC
0         AFDN       chr6        167951905  HIGHRISK_NMIBC
1         AFDN       chr6        167951903   LOWRISK_NMIBC
1         AFDN       chr6        167951904   LOWRISK_NMIBC
1         AFDN       chr6        167951905   LOWRISK_NMIBC
2         AKT1      chr14        104780212   LOWRISK_NMIBC
2         AKT1      chr14        104780213   LOWRISK_NMIBC
2         AKT1      chr14        104780214   LOWRISK_NMIBC
3      ARHGAP5      chr14         32092134            MIBC
3      ARHGAP5      chr14         32092135            MIBC
3      ARHGAP5      chr14         32092136            MIBC
4        ASXL2       chr2         25756052            MIBC
4        ASXL2       chr2         25756053            MIBC
4        ASXL2       chr2         25756054            MIBC
4        ASXL2       chr2         25756064            MIBC
4        ASXL2       chr2         25756065            MIBC
4        ASXL2       chr2         25756066            MIBC
5         BAP1       chr3         52407184            MIBC
5         BAP1       chr3         52407185            MIBC
5         BAP1       chr3         52407186            MIBC
5         BAP1       chr3         52407202            MIBC
5         BAP1       chr3         52407203            MIBC
5         BAP1       chr3         52407204            MIBC
5         BAP1       chr3         52407208            MIBC
5         BAP1       chr3         52407209            MIBC
5         BAP1       chr3         52407210            MIBC
5         BAP1       chr3         52407247            MIBC
5         BAP1       chr3         52407248            MIBC
5         BAP1       chr3         52407249            MIBC
5         BAP1       chr3         52407250            MIBC
5         BAP1       chr3         52407251            MIBC
5         BAP1       chr3         52407252            MIBC
5         BAP1       chr3         52408060            MIBC
5         BAP1       chr3         52408061            MIBC
5         BAP1       chr3         52408062            MIBC
5         BAP1       chr3         52408063            MIBC
5         BAP1       chr3         52408064            MIBC
5         BAP1       chr3         52408065            MIBC
6         BMP6       chr6          7727307            MIBC
6         BMP6       chr6          7727308            MIBC
6         BMP6       chr6          7727309            MIBC
7         BRAF       chr7        140753335            MIBC
7         BRAF       chr7        140753336            MIBC
7         BRAF       chr7        140753337            MIBC
7         BRAF       chr7        140753347            MIBC
7         BRAF       chr7        140753348            MIBC
7         BRAF       chr7        140753349            MIBC
7         BRAF       chr7        140753353            MIBC
7         BRAF       chr7        140753354            MIBC
7         BRAF       chr7        140753355            MIBC
7         BRAF       chr7        140753392            MIBC
7         BRAF       chr7        140753393            MIBC
7         BRAF       chr7        140754187            MIBC
7         BRAF       chr7        140754194            MIBC
7         BRAF       chr7        140754195            MIBC
7         BRAF       chr7        140754196            MIBC
7         BRAF       chr7        140754203            MIBC
7         BRAF       chr7        140754204            MIBC
7         BRAF       chr7        140754205            MIBC
7         BRAF       chr7        140778053            MIBC
7         BRAF       chr7        140778054            MIBC
7         BRAF       chr7        140778055            MIBC
7         BRAF       chr7        140781598            MIBC
7         BRAF       chr7        140781599            MIBC
7         BRAF       chr7        140781600            MIBC
7         BRAF       chr7        140781601            MIBC
7         BRAF       chr7        140781602            MIBC
7         BRAF       chr7        140781603            MIBC
7         BRAF       chr7        140781616            MIBC
7         BRAF       chr7        140781617            MIBC
7         BRAF       chr7        140781618            MIBC
8       CREBBP      chr16          3731303            MIBC
8       CREBBP      chr16          3731304            MIBC
8       CREBBP      chr16          3731305            MIBC
8       CREBBP      chr16          3731372            MIBC
8       CREBBP      chr16          3731373            MIBC
8       CREBBP      chr16          3731374            MIBC
8       CREBBP      chr16          3736758            MIBC
8       CREBBP      chr16          3736759            MIBC
8       CREBBP      chr16          3736760            MIBC
8       CREBBP      chr16          3736764            MIBC
8       CREBBP      chr16          3736765            MIBC
8       CREBBP      chr16          3736766            MIBC
8       CREBBP      chr16          3738645            MIBC
8       CREBBP      chr16          3738646            MIBC
8       CREBBP      chr16          3738647            MIBC
8       CREBBP      chr16          3738648            MIBC
8       CREBBP      chr16          3738649            MIBC
8       CREBBP      chr16          3738650            MIBC
8       CREBBP      chr16          3738651            MIBC
8       CREBBP      chr16          3738652            MIBC
8       CREBBP      chr16          3738653            MIBC
9          DEK       chr6         18263865            MIBC
9          DEK       chr6         18263866            MIBC
9          DEK       chr6         18263867            MIBC
10       EP300      chr22         41169525            MIBC
10       EP300      chr22         41169526            MIBC
10       EP300      chr22         41169527            MIBC
10       EP300      chr22         41169528            MIBC
10       EP300      chr22         41169529            MIBC
10       EP300      chr22         41169530            MIBC
10       EP300      chr22         41169555            MIBC
10       EP300      chr22         41169556            MIBC
10       EP300      chr22         41169557            MIBC
10       EP300      chr22         41169570            MIBC
10       EP300      chr22         41169571            MIBC
10       EP300      chr22         41169572            MIBC
10       EP300      chr22         41170443            MIBC
10       EP300      chr22         41170444            MIBC
10       EP300      chr22         41170445            MIBC
10       EP300      chr22         41170452            MIBC
10       EP300      chr22         41170453            MIBC
10       EP300      chr22         41170454            MIBC
10       EP300      chr22         41170455            MIBC
10       EP300      chr22         41170456            MIBC
10       EP300      chr22         41170457            MIBC
10       EP300      chr22         41170461            MIBC
10       EP300      chr22         41170462            MIBC
10       EP300      chr22         41170463            MIBC
10       EP300      chr22         41170482            MIBC
10       EP300      chr22         41170483            MIBC
10       EP300      chr22         41170484            MIBC
10       EP300      chr22         41170527            MIBC
10       EP300      chr22         41170528            MIBC
10       EP300      chr22         41170529            MIBC
10       EP300      chr22         41176340            MIBC
10       EP300      chr22         41176341            MIBC
10       EP300      chr22         41176342            MIBC
10       EP300      chr22         41176346            MIBC
10       EP300      chr22         41176347            MIBC
10       EP300      chr22         41176348            MIBC
11       ERBB2      chr17         39711939  HIGHRISK_NMIBC
11       ERBB2      chr17         39711940  HIGHRISK_NMIBC
11       ERBB2      chr17         39711941  HIGHRISK_NMIBC
11       ERBB2      chr17         39711954  HIGHRISK_NMIBC
11       ERBB2      chr17         39711955  HIGHRISK_NMIBC
11       ERBB2      chr17         39711956  HIGHRISK_NMIBC
11       ERBB2      chr17         39711963  HIGHRISK_NMIBC
11       ERBB2      chr17         39711964  HIGHRISK_NMIBC
11       ERBB2      chr17         39711965  HIGHRISK_NMIBC
12       ERBB2      chr17         39710409            MIBC
12       ERBB2      chr17         39710410            MIBC
12       ERBB2      chr17         39710411            MIBC
12       ERBB2      chr17         39710418            MIBC
12       ERBB2      chr17         39710419            MIBC
12       ERBB2      chr17         39710420            MIBC
12       ERBB2      chr17         39711954            MIBC
12       ERBB2      chr17         39711955            MIBC
12       ERBB2      chr17         39711956            MIBC
12       ERBB2      chr17         39723649            MIBC
12       ERBB2      chr17         39723650            MIBC
12       ERBB2      chr17         39723651            MIBC
12       ERBB2      chr17         39723966            MIBC
12       ERBB2      chr17         39723967            MIBC
12       ERBB2      chr17         39723968            MIBC
12       ERBB2      chr17         39724002            MIBC
12       ERBB2      chr17         39724003            MIBC
12       ERBB2      chr17         39724004            MIBC
12       ERBB2      chr17         39724008            MIBC
12       ERBB2      chr17         39724009            MIBC
12       ERBB2      chr17         39724010            MIBC
13       ERBB3      chr12         56085001  HIGHRISK_NMIBC
13       ERBB3      chr12         56085002  HIGHRISK_NMIBC
13       ERBB3      chr12         56085003  HIGHRISK_NMIBC
13       ERBB3      chr12         56085004  HIGHRISK_NMIBC
13       ERBB3      chr12         56085005  HIGHRISK_NMIBC
13       ERBB3      chr12         56085006  HIGHRISK_NMIBC
13       ERBB3      chr12         56085070  HIGHRISK_NMIBC
13       ERBB3      chr12         56085071  HIGHRISK_NMIBC
13       ERBB3      chr12         56085072  HIGHRISK_NMIBC
13       ERBB3      chr12         56087869  HIGHRISK_NMIBC
13       ERBB3      chr12         56087870  HIGHRISK_NMIBC
13       ERBB3      chr12         56087871  HIGHRISK_NMIBC
13       ERBB3      chr12         56087875  HIGHRISK_NMIBC
13       ERBB3      chr12         56087876  HIGHRISK_NMIBC
13       ERBB3      chr12         56087877  HIGHRISK_NMIBC
13       ERBB3      chr12         56088021  HIGHRISK_NMIBC
13       ERBB3      chr12         56088022  HIGHRISK_NMIBC
13       ERBB3      chr12         56088023  HIGHRISK_NMIBC
13       ERBB3      chr12         56088138  HIGHRISK_NMIBC
13       ERBB3      chr12         56088139  HIGHRISK_NMIBC
13       ERBB3      chr12         56088140  HIGHRISK_NMIBC
13       ERBB3      chr12         56088653  HIGHRISK_NMIBC
13       ERBB3      chr12         56088654  HIGHRISK_NMIBC
13       ERBB3      chr12         56088655  HIGHRISK_NMIBC
13       ERBB3      chr12         56088753  HIGHRISK_NMIBC
13       ERBB3      chr12         56088754  HIGHRISK_NMIBC
13       ERBB3      chr12         56088755  HIGHRISK_NMIBC
13       ERBB3      chr12         56088822  HIGHRISK_NMIBC
13       ERBB3      chr12         56088823  HIGHRISK_NMIBC
13       ERBB3      chr12         56088824  HIGHRISK_NMIBC
14       ERBB3      chr12         56085031            MIBC
14       ERBB3      chr12         56085032            MIBC
14       ERBB3      chr12         56085033            MIBC
14       ERBB3      chr12         56085067            MIBC
14       ERBB3      chr12         56085068            MIBC
14       ERBB3      chr12         56085069            MIBC
14       ERBB3      chr12         56085070            MIBC
14       ERBB3      chr12         56085071            MIBC
14       ERBB3      chr12         56085072            MIBC
14       ERBB3      chr12         56088021            MIBC
14       ERBB3      chr12         56088022            MIBC
14       ERBB3      chr12         56088023            MIBC
14       ERBB3      chr12         56088138            MIBC
14       ERBB3      chr12         56088139            MIBC
14       ERBB3      chr12         56088140            MIBC
14       ERBB3      chr12         56088753            MIBC
14       ERBB3      chr12         56088754            MIBC
14       ERBB3      chr12         56088755            MIBC
15       ERCC2      chr19         45352527  HIGHRISK_NMIBC
15       ERCC2      chr19         45352528  HIGHRISK_NMIBC
15       ERCC2      chr19         45352529  HIGHRISK_NMIBC
15       ERCC2      chr19         45352557  HIGHRISK_NMIBC
15       ERCC2      chr19         45352558  HIGHRISK_NMIBC
15       ERCC2      chr19         45352559  HIGHRISK_NMIBC
15       ERCC2      chr19         45352572  HIGHRISK_NMIBC
15       ERCC2      chr19         45352573  HIGHRISK_NMIBC
15       ERCC2      chr19         45352574  HIGHRISK_NMIBC
15       ERCC2      chr19         45353084  HIGHRISK_NMIBC
15       ERCC2      chr19         45353085  HIGHRISK_NMIBC
15       ERCC2      chr19         45353086  HIGHRISK_NMIBC
15       ERCC2      chr19         45353093  HIGHRISK_NMIBC
15       ERCC2      chr19         45353094  HIGHRISK_NMIBC
15       ERCC2      chr19         45353095  HIGHRISK_NMIBC
15       ERCC2      chr19         45353096  HIGHRISK_NMIBC
15       ERCC2      chr19         45353097  HIGHRISK_NMIBC
15       ERCC2      chr19         45353098  HIGHRISK_NMIBC
15       ERCC2      chr19         45357297  HIGHRISK_NMIBC
15       ERCC2      chr19         45357298  HIGHRISK_NMIBC
15       ERCC2      chr19         45357299  HIGHRISK_NMIBC
15       ERCC2      chr19         45364312  HIGHRISK_NMIBC
15       ERCC2      chr19         45364313  HIGHRISK_NMIBC
15       ERCC2      chr19         45364314  HIGHRISK_NMIBC
15       ERCC2      chr19         45364324  HIGHRISK_NMIBC
15       ERCC2      chr19         45364325  HIGHRISK_NMIBC
15       ERCC2      chr19         45364326  HIGHRISK_NMIBC
15       ERCC2      chr19         45364428  HIGHRISK_NMIBC
15       ERCC2      chr19         45364429  HIGHRISK_NMIBC
15       ERCC2      chr19         45364430  HIGHRISK_NMIBC
15       ERCC2      chr19         45364515  HIGHRISK_NMIBC
15       ERCC2      chr19         45364516  HIGHRISK_NMIBC
15       ERCC2      chr19         45364517  HIGHRISK_NMIBC
15       ERCC2      chr19         45368732  HIGHRISK_NMIBC
15       ERCC2      chr19         45368733  HIGHRISK_NMIBC
15       ERCC2      chr19         45368734  HIGHRISK_NMIBC
15       ERCC2      chr19         45368930  HIGHRISK_NMIBC
15       ERCC2      chr19         45368931  HIGHRISK_NMIBC
15       ERCC2      chr19         45368932  HIGHRISK_NMIBC
15       ERCC2      chr19         45368939  HIGHRISK_NMIBC
15       ERCC2      chr19         45368940  HIGHRISK_NMIBC
15       ERCC2      chr19         45368941  HIGHRISK_NMIBC
15       ERCC2      chr19         45368948  HIGHRISK_NMIBC
15       ERCC2      chr19         45368949  HIGHRISK_NMIBC
15       ERCC2      chr19         45368950  HIGHRISK_NMIBC
15       ERCC2      chr19         45368951  HIGHRISK_NMIBC
15       ERCC2      chr19         45368952  HIGHRISK_NMIBC
15       ERCC2      chr19         45368953  HIGHRISK_NMIBC
15       ERCC2      chr19         45368954  HIGHRISK_NMIBC
15       ERCC2      chr19         45368955  HIGHRISK_NMIBC
15       ERCC2      chr19         45368956  HIGHRISK_NMIBC
15       ERCC2      chr19         45368960  HIGHRISK_NMIBC
15       ERCC2      chr19         45368961  HIGHRISK_NMIBC
15       ERCC2      chr19         45368962  HIGHRISK_NMIBC
15       ERCC2      chr19         45369106  HIGHRISK_NMIBC
15       ERCC2      chr19         45369107  HIGHRISK_NMIBC
15       ERCC2      chr19         45369108  HIGHRISK_NMIBC
15       ERCC2      chr19         45369115  HIGHRISK_NMIBC
15       ERCC2      chr19         45369116  HIGHRISK_NMIBC
15       ERCC2      chr19         45369117  HIGHRISK_NMIBC
15       ERCC2      chr19         45369121  HIGHRISK_NMIBC
15       ERCC2      chr19         45369122  HIGHRISK_NMIBC
15       ERCC2      chr19         45369123  HIGHRISK_NMIBC
15       ERCC2      chr19         45369127  HIGHRISK_NMIBC
15       ERCC2      chr19         45369128  HIGHRISK_NMIBC
15       ERCC2      chr19         45369129  HIGHRISK_NMIBC
15       ERCC2      chr19         45370166  HIGHRISK_NMIBC
15       ERCC2      chr19         45370167  HIGHRISK_NMIBC
15       ERCC2      chr19         45370168  HIGHRISK_NMIBC
15       ERCC2      chr19         45370169  HIGHRISK_NMIBC
15       ERCC2      chr19         45370170  HIGHRISK_NMIBC
15       ERCC2      chr19         45370171  HIGHRISK_NMIBC
15       ERCC2      chr19         45370184  HIGHRISK_NMIBC
15       ERCC2      chr19         45370185  HIGHRISK_NMIBC
15       ERCC2      chr19         45370186  HIGHRISK_NMIBC
16       ERCC2      chr19         45352527            MIBC
16       ERCC2      chr19         45352528            MIBC
16       ERCC2      chr19         45352529            MIBC
16       ERCC2      chr19         45352554            MIBC
16       ERCC2      chr19         45352555            MIBC
16       ERCC2      chr19         45352556            MIBC
16       ERCC2      chr19         45352557            MIBC
16       ERCC2      chr19         45352558            MIBC
16       ERCC2      chr19         45352559            MIBC
16       ERCC2      chr19         45352566            MIBC
16       ERCC2      chr19         45352567            MIBC
16       ERCC2      chr19         45352568            MIBC
16       ERCC2      chr19         45352575            MIBC
16       ERCC2      chr19         45352576            MIBC
16       ERCC2      chr19         45352577            MIBC
16       ERCC2      chr19         45353087            MIBC
16       ERCC2      chr19         45353088            MIBC
16       ERCC2      chr19         45353089            MIBC
16       ERCC2      chr19         45353093            MIBC
16       ERCC2      chr19         45353094            MIBC
16       ERCC2      chr19         45353095            MIBC
16       ERCC2      chr19         45353096            MIBC
16       ERCC2      chr19         45353097            MIBC
16       ERCC2      chr19         45353098            MIBC
16       ERCC2      chr19         45353111            MIBC
16       ERCC2      chr19         45353112            MIBC
16       ERCC2      chr19         45353113            MIBC
16       ERCC2      chr19         45357477            MIBC
16       ERCC2      chr19         45357478            MIBC
16       ERCC2      chr19         45357479            MIBC
16       ERCC2      chr19         45357522            MIBC
16       ERCC2      chr19         45357523            MIBC
16       ERCC2      chr19         45357524            MIBC
16       ERCC2      chr19         45364312            MIBC
16       ERCC2      chr19         45364313            MIBC
16       ERCC2      chr19         45364314            MIBC
16       ERCC2      chr19         45364324            MIBC
16       ERCC2      chr19         45364325            MIBC
16       ERCC2      chr19         45364326            MIBC
16       ERCC2      chr19         45364428            MIBC
16       ERCC2      chr19         45364429            MIBC
16       ERCC2      chr19         45364430            MIBC
16       ERCC2      chr19         45364515            MIBC
16       ERCC2      chr19         45364516            MIBC
16       ERCC2      chr19         45364517            MIBC
16       ERCC2      chr19         45368711            MIBC
16       ERCC2      chr19         45368712            MIBC
16       ERCC2      chr19         45368713            MIBC
16       ERCC2      chr19         45368732            MIBC

In [78]:
dk

     chromosome        pos     CANCER_TYPE
0          chr6  167889230  HIGHRISK_NMIBC
1          chr6  167889231  HIGHRISK_NMIBC
2          chr6  167889232  HIGHRISK_NMIBC
3          chr6  167951903  HIGHRISK_NMIBC
4          chr6  167951904  HIGHRISK_NMIBC
5          chr6  167951905  HIGHRISK_NMIBC
6          chr6  167951903   LOWRISK_NMIBC
7          chr6  167951904   LOWRISK_NMIBC
8          chr6  167951905   LOWRISK_NMIBC
9         chr14  104780212   LOWRISK_NMIBC
10        chr14  104780213   LOWRISK_NMIBC
11        chr14  104780214   LOWRISK_NMIBC
12        chr14   32092134            MIBC
13        chr14   32092135            MIBC
14        chr14   32092136            MIBC
15         chr2   25756052            MIBC
16         chr2   25756053            MIBC
17         chr2   25756054            MIBC
18         chr2   25756064            MIBC
19         chr2   25756065            MIBC
20         chr2   25756066            MIBC
21         chr3   52407184            MIBC
22         chr3   52407185            MIBC
23         chr3   52407186            MIBC
24         chr3   52407202            MIBC
25         chr3   52407203            MIBC
26         chr3   52407204            MIBC
27         chr3   52407208            MIBC
28         chr3   52407209            MIBC
29         chr3   52407210            MIBC
30         chr3   52407247            MIBC
31         chr3   52407248            MIBC
32         chr3   52407249            MIBC
33         chr3   52407250            MIBC
34         chr3   52407251            MIBC
35         chr3   52407252            MIBC
36         chr3   52408060            MIBC
37         chr3   52408061            MIBC
38         chr3   52408062            MIBC
39         chr3   52408063            MIBC
40         chr3   52408064            MIBC
41         chr3   52408065            MIBC
42         chr6    7727307            MIBC
43         chr6    7727308            MIBC
44         chr6    7727309            MIBC
45         chr7  140753335            MIBC
46         chr7  140753336            MIBC
47         chr7  140753337            MIBC
48         chr7  140753347            MIBC
49         chr7  140753348            MIBC
50         chr7  140753349            MIBC
51         chr7  140753353            MIBC
52         chr7  140753354            MIBC
53         chr7  140753355            MIBC
54         chr7  140753392            MIBC
55         chr7  140753393            MIBC
56         chr7  140754187            MIBC
57         chr7  140754194            MIBC
58         chr7  140754195            MIBC
59         chr7  140754196            MIBC
60         chr7  140754203            MIBC
61         chr7  140754204            MIBC
62         chr7  140754205            MIBC
63         chr7  140778053            MIBC
64         chr7  140778054            MIBC
65         chr7  140778055            MIBC
66         chr7  140781598            MIBC
67         chr7  140781599            MIBC
68         chr7  140781600            MIBC
69         chr7  140781601            MIBC
70         chr7  140781602            MIBC
71         chr7  140781603            MIBC
72         chr7  140781616            MIBC
73         chr7  140781617            MIBC
74         chr7  140781618            MIBC
75        chr16    3731303            MIBC
76        chr16    3731304            MIBC
77        chr16    3731305            MIBC
78        chr16    3731372            MIBC
79        chr16    3731373            MIBC
80        chr16    3731374            MIBC
81        chr16    3736758            MIBC
82        chr16    3736759            MIBC
83        chr16    3736760            MIBC
84        chr16    3736764            MIBC
85        chr16    3736765            MIBC
86        chr16    3736766            MIBC
87        chr16    3738645            MIBC
88        chr16    3738646            MIBC
89        chr16    3738647            MIBC
90        chr16    3738648            MIBC
91        chr16    3738649            MIBC
92        chr16    3738650            MIBC
93        chr16    3738651            MIBC
94        chr16    3738652            MIBC
95        chr16    3738653            MIBC
96         chr6   18263865            MIBC
97         chr6   18263866            MIBC
98         chr6   18263867            MIBC
99        chr22   41169525            MIBC
100       chr22   41169526            MIBC
101       chr22   41169527            MIBC
102       chr22   41169528            MIBC
103       chr22   41169529            MIBC
104       chr22   41169530            MIBC
105       chr22   41169555            MIBC
106       chr22   41169556            MIBC
107       chr22   41169557            MIBC
108       chr22   41169570            MIBC
109       chr22   41169571            MIBC
110       chr22   41169572            MIBC
111       chr22   41170443            MIBC
112       chr22   41170444            MIBC
113       chr22   41170445            MIBC
114       chr22   41170452            MIBC
115       chr22   41170453            MIBC
116       chr22   41170454            MIBC
117       chr22   41170455            MIBC
118       chr22   41170456            MIBC
119       chr22   41170457            MIBC
120       chr22   41170461            MIBC
121       chr22   41170462            MIBC
122       chr22   41170463            MIBC
123       chr22   41170482            MIBC
124       chr22   41170483            MIBC
125       chr22   41170484            MIBC
126       chr22   41170527            MIBC
127       chr22   41170528            MIBC
128       chr22   41170529            MIBC
129       chr22   41176340            MIBC
130       chr22   41176341            MIBC
131       chr22   41176342            MIBC
132       chr22   41176346            MIBC
133       chr22   41176347            MIBC
134       chr22   41176348            MIBC
135       chr17   39711939  HIGHRISK_NMIBC
136       chr17   39711940  HIGHRISK_NMIBC
137       chr17   39711941  HIGHRISK_NMIBC
138       chr17   39711954  HIGHRISK_NMIBC
139       chr17   39711955  HIGHRISK_NMIBC
140       chr17   39711956  HIGHRISK_NMIBC
141       chr17   39711963  HIGHRISK_NMIBC
142       chr17   39711964  HIGHRISK_NMIBC
143       chr17   39711965  HIGHRISK_NMIBC
144       chr17   39710409            MIBC
145       chr17   39710410            MIBC
146       chr17   39710411            MIBC
147       chr17   39710418            MIBC
148       chr17   39710419            MIBC
149       chr17   39710420            MIBC
150       chr17   39711954            MIBC
151       chr17   39711955            MIBC
152       chr17   39711956            MIBC
153       chr17   39723649            MIBC
154       chr17   39723650            MIBC
155       chr17   39723651            MIBC
156       chr17   39723966            MIBC
157       chr17   39723967            MIBC
158       chr17   39723968            MIBC
159       chr17   39724002            MIBC
160       chr17   39724003            MIBC
161       chr17   39724004            MIBC
162       chr17   39724008            MIBC
163       chr17   39724009            MIBC
164       chr17   39724010            MIBC
165       chr12   56085001  HIGHRISK_NMIBC
166       chr12   56085002  HIGHRISK_NMIBC
167       chr12   56085003  HIGHRISK_NMIBC
168       chr12   56085004  HIGHRISK_NMIBC
169       chr12   56085005  HIGHRISK_NMIBC
170       chr12   56085006  HIGHRISK_NMIBC
171       chr12   56085070  HIGHRISK_NMIBC
172       chr12   56085071  HIGHRISK_NMIBC
173       chr12   56085072  HIGHRISK_NMIBC
174       chr12   56087869  HIGHRISK_NMIBC
175       chr12   56087870  HIGHRISK_NMIBC
176       chr12   56087871  HIGHRISK_NMIBC
177       chr12   56087875  HIGHRISK_NMIBC
178       chr12   56087876  HIGHRISK_NMIBC
179       chr12   56087877  HIGHRISK_NMIBC
180       chr12   56088021  HIGHRISK_NMIBC
181       chr12   56088022  HIGHRISK_NMIBC
182       chr12   56088023  HIGHRISK_NMIBC
183       chr12   56088138  HIGHRISK_NMIBC
184       chr12   56088139  HIGHRISK_NMIBC
185       chr12   56088140  HIGHRISK_NMIBC
186       chr12   56088653  HIGHRISK_NMIBC
187       chr12   56088654  HIGHRISK_NMIBC
188       chr12   56088655  HIGHRISK_NMIBC
189       chr12   56088753  HIGHRISK_NMIBC
190       chr12   56088754  HIGHRISK_NMIBC
191       chr12   56088755  HIGHRISK_NMIBC
192       chr12   56088822  HIGHRISK_NMIBC
193       chr12   56088823  HIGHRISK_NMIBC
194       chr12   56088824  HIGHRISK_NMIBC
195       chr12   56085031            MIBC
196       chr12   56085032            MIBC
197       chr12   56085033            MIBC
198       chr12   56085067            MIBC
199       chr12   56085068            MIBC
200       chr12   56085069            MIBC
201       chr12   56085070            MIBC
202       chr12   56085071            MIBC
203       chr12   56085072            MIBC
204       chr12   56088021            MIBC
205       chr12   56088022            MIBC
206       chr12   56088023            MIBC
207       chr12   56088138            MIBC
208       chr12   56088139            MIBC
209       chr12   56088140            MIBC
210       chr12   56088753            MIBC
211       chr12   56088754            MIBC
212       chr12   56088755            MIBC
213       chr19   45352527  HIGHRISK_NMIBC
214       chr19   45352528  HIGHRISK_NMIBC
215       chr19   45352529  HIGHRISK_NMIBC
216       chr19   45352557  HIGHRISK_NMIBC
217       chr19   45352558  HIGHRISK_NMIBC
218       chr19   45352559  HIGHRISK_NMIBC
219       chr19   45352572  HIGHRISK_NMIBC
220       chr19   45352573  HIGHRISK_NMIBC
221       chr19   45352574  HIGHRISK_NMIBC
222       chr19   45353084  HIGHRISK_NMIBC
223       chr19   45353085  HIGHRISK_NMIBC
224       chr19   45353086  HIGHRISK_NMIBC
225       chr19   45353093  HIGHRISK_NMIBC
226       chr19   45353094  HIGHRISK_NMIBC
227       chr19   45353095  HIGHRISK_NMIBC
228       chr19   45353096  HIGHRISK_NMIBC
229       chr19   45353097  HIGHRISK_NMIBC
230       chr19   45353098  HIGHRISK_NMIBC
231       chr19   45357297  HIGHRISK_NMIBC
232       chr19   45357298  HIGHRISK_NMIBC
233       chr19   45357299  HIGHRISK_NMIBC
234       chr19   45364312  HIGHRISK_NMIBC
235       chr19   45364313  HIGHRISK_NMIBC
236       chr19   45364314  HIGHRISK_NMIBC
237       chr19   45364324  HIGHRISK_NMIBC
238       chr19   45364325  HIGHRISK_NMIBC
239       chr19   45364326  HIGHRISK_NMIBC
240       chr19   45364428  HIGHRISK_NMIBC
241       chr19   45364429  HIGHRISK_NMIBC
242       chr19   45364430  HIGHRISK_NMIBC
243       chr19   45364515  HIGHRISK_NMIBC
244       chr19   45364516  HIGHRISK_NMIBC
245       chr19   45364517  HIGHRISK_NMIBC
246       chr19   45368732  HIGHRISK_NMIBC
247       chr19   45368733  HIGHRISK_NMIBC
248       chr19   45368734  HIGHRISK_NMIBC
249       chr19   45368930  HIGHRISK_NMIBC
250       chr19   45368931  HIGHRISK_NMIBC
251       chr19   45368932  HIGHRISK_NMIBC
252       chr19   45368939  HIGHRISK_NMIBC
253       chr19   45368940  HIGHRISK_NMIBC
254       chr19   45368941  HIGHRISK_NMIBC
255       chr19   45368948  HIGHRISK_NMIBC
256       chr19   45368949  HIGHRISK_NMIBC
257       chr19   45368950  HIGHRISK_NMIBC
258       chr19   45368951  HIGHRISK_NMIBC
259       chr19   45368952  HIGHRISK_NMIBC
260       chr19   45368953  HIGHRISK_NMIBC
261       chr19   45368954  HIGHRISK_NMIBC
262       chr19   45368955  HIGHRISK_NMIBC
263       chr19   45368956  HIGHRISK_NMIBC
264       chr19   45368960  HIGHRISK_NMIBC
265       chr19   45368961  HIGHRISK_NMIBC
266       chr19   45368962  HIGHRISK_NMIBC
267       chr19   45369106  HIGHRISK_NMIBC
268       chr19   45369107  HIGHRISK_NMIBC
269       chr19   45369108  HIGHRISK_NMIBC
270       chr19   45369115  HIGHRISK_NMIBC
271       chr19   45369116  HIGHRISK_NMIBC
272       chr19   45369117  HIGHRISK_NMIBC
273       chr19   45369121  HIGHRISK_NMIBC
274       chr19   45369122  HIGHRISK_NMIBC
275       chr19   45369123  HIGHRISK_NMIBC
276       chr19   45369127  HIGHRISK_NMIBC
277       chr19   45369128  HIGHRISK_NMIBC
278       chr19   45369129  HIGHRISK_NMIBC
279       chr19   45370166  HIGHRISK_NMIBC
280       chr19   45370167  HIGHRISK_NMIBC
281       chr19   45370168  HIGHRISK_NMIBC
282       chr19   45370169  HIGHRISK_NMIBC
283       chr19   45370170  HIGHRISK_NMIBC
284       chr19   45370171  HIGHRISK_NMIBC
285       chr19   45370184  HIGHRISK_NMIBC
286       chr19   45370185  HIGHRISK_NMIBC
287       chr19   45370186  HIGHRISK_NMIBC
288       chr19   45352527            MIBC
289       chr19   45352528            MIBC
290       chr19   45352529            MIBC
291       chr19   45352554            MIBC
292       chr19   45352555            MIBC
293       chr19   45352556            MIBC
294       chr19   45352557            MIBC
295       chr19   45352558            MIBC
296       chr19   45352559            MIBC
297       chr19   45352566            MIBC
298       chr19   45352567            MIBC
299       chr19   45352568            MIBC
300       chr19   45352575            MIBC
301       chr19   45352576            MIBC
302       chr19   45352577            MIBC
303       chr19   45353087            MIBC
304       chr19   45353088            MIBC
305       chr19   45353089            MIBC
306       chr19   45353093            MIBC
307       chr19   45353094            MIBC
308       chr19   45353095            MIBC
309       chr19   45353096            MIBC
310       chr19   45353097            MIBC
311       chr19   45353098            MIBC
312       chr19   45353111            MIBC
313       chr19   45353112            MIBC
314       chr19   45353113            MIBC
315       chr19   45357477            MIBC
316       chr19   45357478            MIBC
317       chr19   45357479            MIBC
318       chr19   45357522            MIBC
319       chr19   45357523            MIBC
320       chr19   45357524            MIBC
321       chr19   45364312            MIBC
322       chr19   45364313            MIBC
323       chr19   45364314            MIBC
324       chr19   45364324            MIBC
325       chr19   45364325            MIBC
326       chr19   45364326            MIBC
327       chr19   45364428            MIBC
328       chr19   45364429            MIBC
329       chr19   45364430            MIBC
330       chr19   45364515            MIBC
331       chr19   45364516            MIBC
332       chr19   45364517            MIBC
333       chr19   45368711            MIBC
334       chr19   45368712            MIBC
335       chr19   45368713            MIBC
336       chr19   45368732            MIBC
337       chr19   45368733            MIBC
338       chr19   45368734            MIBC
339       chr19   45368936            MIBC
340       chr19   45368937            MIBC
341       chr19   45368938            MIBC
342       chr19   45368939            MIBC
343       chr19   45368940            MIBC
344       chr19   45368941            MIBC
345       chr19   45368948            MIBC
346       chr19   45368949            MIBC
347       chr19   45368950            MIBC
348       chr19   45368951            MIBC
349       chr19   45368952            MIBC
350       chr19   45368953            MIBC
351       chr19   45368954            MIBC
352       chr19   45368955            MIBC
353       chr19   45368956            MIBC
354       chr19   45368960            MIBC
355       chr19   45368961            MIBC
356       chr19   45368962            MIBC
357       chr19   45369106            MIBC
358       chr19   45369107            MIBC
359       chr19   45369108            MIBC
360       chr19   45369121            MIBC
361       chr19   45369122            MIBC
362       chr19   45369123            MIBC
363       chr19   45370187            MIBC
364       chr19   45370188            MIBC
365       chr19   45370189            MIBC
366       chr19   45370196            MIBC
367       chr19   45370197            MIBC
368       chr19   45370198            MIBC
369       chr17   43545338            MIBC
370       chr17   43545339            MIBC
371       chr17   43545340            MIBC
372        chr4  152324284  HIGHRISK_NMIBC
373        chr4  152324285  HIGHRISK_NMIBC
374        chr4  152324286  HIGHRISK_NMIBC
375        chr4  152326006  HIGHRISK_NMIBC
376        chr4  152326007  HIGHRISK_NMIBC
377        chr4  152326008  HIGHRISK_NMIBC
378        chr4  152326012  HIGHRISK_NMIBC
379        chr4  152326013  HIGHRISK_NMIBC
380        chr4  152326014  HIGHRISK_NMIBC
381        chr4  152326015  HIGHRISK_NMIBC
382        chr4  152326016  HIGHRISK_NMIBC
383        chr4  152326017  HIGHRISK_NMIBC
384        chr4  152326090  HIGHRISK_NMIBC
385        chr4  152326091  HIGHRISK_NMIBC
386        chr4  152326092  HIGHRISK_NMIBC
387        chr4  152326093  HIGHRISK_NMIBC
388        chr4  152326094  HIGHRISK_NMIBC
389        chr4  152326095  HIGHRISK_NMIBC
390        chr4  152326102  HIGHRISK_NMIBC
391        chr4  152326103  HIGHRISK_NMIBC
392        chr4  152326104  HIGHRISK_NMIBC
393        chr4  152326135  HIGHRISK_NMIBC
394        chr4  152326136  HIGHRISK_NMIBC
395        chr4  152326137  HIGHRISK_NMIBC
396        chr4  152326150  HIGHRISK_NMIBC
397        chr4  152326151  HIGHRISK_NMIBC
398        chr4  152326152  HIGHRISK_NMIBC
399        chr4  152326201  HIGHRISK_NMIBC
400        chr4  152326202  HIGHRISK_NMIBC
401        chr4  152326203  HIGHRISK_NMIBC
402        chr4  152326213  HIGHRISK_NMIBC
403        chr4  152326214  HIGHRISK_NMIBC
404        chr4  152326215  HIGHRISK_NMIBC
405        chr4  152328231  HIGHRISK_NMIBC
406        chr4  152328232  HIGHRISK_NMIBC
407        chr4  152328233  HIGHRISK_NMIBC
408        chr4  152328348  HIGHRISK_NMIBC
409        chr4  152328349  HIGHRISK_NMIBC
410        chr4  152328350  HIGHRISK_NMIBC
411        chr4  152326012            MIBC
412        chr4  152326013            MIBC
413        chr4  152326014            MIBC
414        chr4  152326030            MIBC
415        chr4  152326031            MIBC
416        chr4  152326032            MIBC
417        chr4  152326090            MIBC
418        chr4  152326091            MIBC
419        chr4  152326092            MIBC
420        chr4  152326093            MIBC
421        chr4  152326094            MIBC
422        chr4  152326095            MIBC
423        chr4  152326099            MIBC
424        chr4  152326100            MIBC
425        chr4  152326101            MIBC
426        chr4  152326135            MIBC
427        chr4  152326136            MIBC
428        chr4  152326137            MIBC
429        chr4  152326201            MIBC
430        chr4  152326202            MIBC
431        chr4  152326203            MIBC
432        chr4  152326207            MIBC
433        chr4  152326208            MIBC
434        chr4  152326209            MIBC
435        chr4  152326213            MIBC
436        chr4  152326214            MIBC
437        chr4  152326215            MIBC
438        chr4  152326219            MIBC
439        chr4  152326220            MIBC
440        chr4  152326221            MIBC
441        chr4  152328231            MIBC
442        chr4  152328232            MIBC
443        chr4  152328233            MIBC
444        chr4  152328348            MIBC
445        chr4  152328349            MIBC
446        chr4  152328350            MIBC
447        chr4  152329714            MIBC
448        chr4  152329715            MIBC
449        chr4  152329716            MIBC
450        chr4  152329753            MIBC
451        chr4  152329754            MIBC
452        chr4  152329755            MIBC
453        chr4    1801837  HIGHRISK_NMIBC
454        chr4    1801838  HIGHRISK_NMIBC
455        chr4    1801839  HIGHRISK_NMIBC
456        chr4    1801840  HIGHRISK_NMIBC
457        chr4    1801841  HIGHRISK_NMIBC
458        chr4    1801842  HIGHRISK_NMIBC
459        chr4    1804362  HIGHRISK_NMIBC
460        chr4    1804363  HIGHRISK_NMIBC
461        chr4    1804364  HIGHRISK_NMIBC
462        chr4    1804365  HIGHRISK_NMIBC
463        chr4    1804366  HIGHRISK_NMIBC

In [82]:
result_df.shape, dk.shape

((1242, 4), (1242, 3))